name: daily-top-stock

on:
  schedule:
    - cron: '0 21 * * 1-5' # At 09:00 PM UTC Every Monday to Friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # Checkout the repository content to Github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: run daily-top-stock # Run the python script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
        run: python main.py
